workflows: 
  ios-release-no-shorebird: 
    name: iOS Release 
    environment: 
      flutter: stable 
      xcode: latest 
    scripts: 
      - flutter pub get 
      - flutter build ios --simulator 
      - cd build/ios/iphonesimulator 
      - zip -r ../../ipa/Runner.app.zip Runner.app 
    artifacts: 
      - build/ios/ipa/Runner.app.zip