name: prokit_socialv
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # ✅ Dart 3 desteği

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_vector_icons: ^2.0.0

  # Images
  image_picker: ^1.1.2

  # APIs
  http: ^1.4.0
  intl: ^0.19.0
  html: ^0.15.0

  # Common packages
  nb_utils: ^7.0.7
  google_fonts: ^6.2.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.1.1

  # Story
  story_view: ^0.16.5
  flutter_reaction_button: ^3.0.0+3

  # State Management Technique
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  csc_picker: ^0.2.6
  file_picker: ^8.3.2
  open_filex: ^4.3.2
  dash_chat_2: ^0.0.15
  firebase_messaging: ^15.2.7
  rxdart: ^0.27.7
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  jwt_decoder: ^2.0.1
  grouped_list: ^6.0.0
  background_fetch: ^1.1.3
  intl_translation: ^0.20.1
  google_mobile_ads: ^5.2.0
  
  purchases_flutter: ^8.10.3
  dotted_border: ^2.0.0+3
  agora_rtc_engine: ^6.5.2
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^11.0.0
  in_app_purchase: ^3.1.5

  screenshot: ^3.0.0
  image: ^4.5.4

  logger: ^2.0.2+1 # Or the latest version
  path_provider: ^2.1.3 # Needed to find a suitable directory for logs


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  mobx_codegen: ^2.0.6

flutter:
  uses-material-design: true

  assets:
    - images/socialv/posts/
    - images/socialv/faces/
    - images/socialv/
    - images/socialv/icons/
    - images/socialv/gifs/
