// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uRotz985DzZrwweAbH63GvYFucQ1Aew',
    appId: '1:885039416228:android:46b9306ddf9f93f19ef731',
    messagingSenderId: '885039416228',
    projectId: 'socialmedia-7c054',
    storageBucket: 'socialmedia-7c054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN1FlABrwjmxG_VBhSYOPm8-5W_HzCdzY',
    appId: '1:885039416228:ios:37b7208261b73a469ef731',
    messagingSenderId: '885039416228',
    projectId: 'socialmedia-7c054',
    storageBucket: 'socialmedia-7c054.appspot.com',
    androidClientId:
        '885039416228-39u6keasgi50plkfck0uib48o11gpaid.apps.googleusercontent.com',
    iosClientId:
        '885039416228-cip8nj2mfnp192r9a4ouesgc94nildj3.apps.googleusercontent.com',
    iosBundleId: 'com.neilb.socialite',
  );
}
